### PR TITLE
Dynamic environments

### PR DESCRIPTION
**Pull request by tokejepsen**
This PR is an implementation of the suggested workflow here; https://github.com/tokejepsen/ftrack-hooks/pull/14#issuecomment-329133867

### CODE REVIEW

**Comment by mkolar** [comment]
I like it. It streamlines the logic and catches most, if not all cases I can think of. I'll try giving it a shot tomorrow and merging afterwards

**Comment by tokejepsen** [comment]
Did you get a chance to try this out?

**Comment by mkolar** [comment]
unfortunately I didn't had full hands of other things. Hopefully tomorrow.

**Comment by tokejepsen** [comment]
Going to put this into production now, and get some proper testing.

**Comment by mkolar** [comment]
great I'll try again today to see if it's working for us now

**Comment by tokejepsen** [comment]
Just had a good idea from a user;

**Motivation**

It can be tricky to troubleshoot the "environment" attribute, and coordinate with the files available locally.

**Implementation**

An action for selecting which environments to add to an entity.

**Comment by mkolar** [comment]
Very good idea actually. We have very simple environments for now, but I can imagine this being a pain in more complex setups

**Comment by tokejepsen** [comment]
This has been working great that last two weeks.

Did you get a chance to test it on your side?

**Comment by tokejepsen** [comment]
What do we think about a merge for this?

**Comment by tokejepsen** [comment]
This got merged with a new PR, directly into the origin repository.

**Pull request closed without merging**
